**NUMPY :**
NumPy is a Python library that provides a simple yet powerful data structure: the n-dimensional array.
This is the foundation on which almost all the power of Python's data science toolkit is built,
Numpy stands for numerical python.

Numpy fuctionaity is used other  popular packages including Pandas and matlbplot.
Numpy written in C which much faster than python.
numpy array are used with homogenous (same) data types only,on the other hand list uses diffrent or any datatype.
Numpy has ability to divide up sub-task and run them parallel.






USES -->
1:Efficient Numerical Computation
2:Array Operations
3:Data Manipulation
4:Integration with Other Libraries.

INSTALLING NUMPY: pip install numpy


IMPORTING NUMPY : import numpy as np

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


DIMENSIONS IN ARRAYS #

1-D ARRAY
2-D ARRAY
3-D ARRAY
4-D ARRAY


In [20]:
import numpy as np
a=np.array(42) # 0-dimension
b=np.array([1,2,3,4,5]) # 1-dimension
c=np.array([[1,2,3],[4,5,6]]) # 2-dimension
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # 3-dimension
print(a,"\n")
print(b,"\n")
print(c,"\n")
print(d,"\n")

42 

[1 2 3 4 5] 

[[1 2 3]
 [4 5 6]] 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 



ACCESSING ELEMENTS FROM ARRAY :

In [4]:

import numpy as np
arr=np.array([1,34,3,45600,4,4,5,5,96,7,89,855])
print(arr[9:])
print(arr[-3:])

print(type(arr))

[  7  89 855]
[  7  89 855]
<class 'numpy.ndarray'>


In [7]:
arr.size

12

In [8]:
import numpy as np
arr3=np.random.randint(1,200,(5,10,5))
arr3

array([[[139, 113, 175,  68,  94],
        [ 77,  92, 187,  42,  77],
        [ 83,  53, 161,  86, 147],
        [ 99,  58, 146,   2,  68],
        [  7,  15,  10,  87,  34],
        [178, 132, 172,  17, 139],
        [  8, 117, 116,  55,  80],
        [ 10, 146,  48,  69,  66],
        [ 78,  93,  28,  25,  89],
        [178,  98, 167, 104, 182]],

       [[197, 194, 160, 146, 149],
        [165, 104, 145, 110,  91],
        [ 58, 101, 113, 107, 138],
        [ 17,  21, 145,  96,  56],
        [  3,  38,   5,   2,  47],
        [164,  41,  14,  20, 123],
        [ 16,  69, 147,  59,  87],
        [ 53, 136, 133, 104,  54],
        [104, 139, 171, 115, 121],
        [ 97, 133, 112,  32, 185]],

       [[158, 175,  16, 120, 110],
        [159, 110,   9, 148,  26],
        [173,  53, 144, 180,  11],
        [139, 110,  66,  17,  13],
        [ 52, 131, 172, 156, 162],
        [137,  16,   7,  51, 110],
        [ 30,  65, 178, 118, 173],
        [ 93,  30,  90, 152, 147],
        [ 17, 13

access with table , row and column.

In [16]:
arr3[-5:-3,-1:]

array([[[178,  98, 167, 104, 182]],

       [[ 97, 133, 112,  32, 185]]])

In [18]:
arr3[0:5,6: ]

array([[[  8, 117, 116,  55,  80],
        [ 10, 146,  48,  69,  66],
        [ 78,  93,  28,  25,  89],
        [178,  98, 167, 104, 182]],

       [[ 16,  69, 147,  59,  87],
        [ 53, 136, 133, 104,  54],
        [104, 139, 171, 115, 121],
        [ 97, 133, 112,  32, 185]],

       [[ 30,  65, 178, 118, 173],
        [ 93,  30,  90, 152, 147],
        [ 17, 138, 148, 165,  19],
        [106,  95, 149,  93, 123]],

       [[ 98, 159,  46,  96,  43],
        [133, 187,  38, 109, 171],
        [ 75, 100,  51, 172,  25],
        [134, 188,  25,  68, 157]],

       [[198, 139,  61,  37, 179],
        [ 11, 111,  48,  34, 101],
        [183, 115, 125,   2,  22],
        [120, 158, 179, 163, 500]]])

access with row and column

In [11]:
arr3[0:3]

array([[[139, 113, 175,  68,  94],
        [ 77,  92, 187,  42,  77],
        [ 83,  53, 161,  86, 147],
        [ 99,  58, 146,   2,  68],
        [  7,  15,  10,  87,  34],
        [178, 132, 172,  17, 139],
        [  8, 117, 116,  55,  80],
        [ 10, 146,  48,  69,  66],
        [ 78,  93,  28,  25,  89],
        [178,  98, 167, 104, 182]],

       [[197, 194, 160, 146, 149],
        [165, 104, 145, 110,  91],
        [ 58, 101, 113, 107, 138],
        [ 17,  21, 145,  96,  56],
        [  3,  38,   5,   2,  47],
        [164,  41,  14,  20, 123],
        [ 16,  69, 147,  59,  87],
        [ 53, 136, 133, 104,  54],
        [104, 139, 171, 115, 121],
        [ 97, 133, 112,  32, 185]],

       [[158, 175,  16, 120, 110],
        [159, 110,   9, 148,  26],
        [173,  53, 144, 180,  11],
        [139, 110,  66,  17,  13],
        [ 52, 131, 172, 156, 162],
        [137,  16,   7,  51, 110],
        [ 30,  65, 178, 118, 173],
        [ 93,  30,  90, 152, 147],
        [ 17, 13

In [14]:
arr3[0:,-1]

array([[178,  98, 167, 104, 182],
       [ 97, 133, 112,  32, 185],
       [106,  95, 149,  93, 123],
       [134, 188,  25,  68, 157],
       [120, 158, 179, 163, 500]])

REPLACING ONE ELEMENT WITH ANOTHER ONE

In [17]:
arr3[-1,-1,-1]=500
arr3

array([[[139, 113, 175,  68,  94],
        [ 77,  92, 187,  42,  77],
        [ 83,  53, 161,  86, 147],
        [ 99,  58, 146,   2,  68],
        [  7,  15,  10,  87,  34],
        [178, 132, 172,  17, 139],
        [  8, 117, 116,  55,  80],
        [ 10, 146,  48,  69,  66],
        [ 78,  93,  28,  25,  89],
        [178,  98, 167, 104, 182]],

       [[197, 194, 160, 146, 149],
        [165, 104, 145, 110,  91],
        [ 58, 101, 113, 107, 138],
        [ 17,  21, 145,  96,  56],
        [  3,  38,   5,   2,  47],
        [164,  41,  14,  20, 123],
        [ 16,  69, 147,  59,  87],
        [ 53, 136, 133, 104,  54],
        [104, 139, 171, 115, 121],
        [ 97, 133, 112,  32, 185]],

       [[158, 175,  16, 120, 110],
        [159, 110,   9, 148,  26],
        [173,  53, 144, 180,  11],
        [139, 110,  66,  17,  13],
        [ 52, 131, 172, 156, 162],
        [137,  16,   7,  51, 110],
        [ 30,  65, 178, 118, 173],
        [ 93,  30,  90, 152, 147],
        [ 17, 13

RESHAPING ARRAY ------------

In [21]:
np.arange(60)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [22]:
np.arange(60).reshape(20,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [23]:
arr45=np.arange(60).reshape(2,15,2)
arr45

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]])

In [24]:
arr45.ravel() #from nd to 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [25]:
arr45.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [26]:
arr=np.random.randint(1,200,(5,3))
arr

array([[167, 146, 197],
       [  1, 118,   9],
       [  8, 190,  50],
       [ 68, 111,  78],
       [108,  67, 163]])

In [27]:
arr.shape

(5, 3)

MATH OPERATIONS -------------------

In [31]:
import numpy as np
a=np.array([1,3,5,6,9])
a+10


array([11, 13, 15, 16, 19])

In [32]:
a-10

array([-9, -7, -5, -4, -1])

In [33]:
a*10

array([10, 30, 50, 60, 90])

In [34]:
a/10

array([0.1, 0.3, 0.5, 0.6, 0.9])

In [35]:
np.square(a)

array([ 1,  9, 25, 36, 81])

In [40]:
a=np.array([1,3,5])
c=np.array([2,5,4])
np.add(a,c) #Adding opertion of 2 d array

array([3, 8, 9])

In [43]:
np.subtract(a,c) #substract opertion of 2 d array

array([-1, -2,  1])

In [42]:
np.multiply(a,c) #multiplication opertion of 2 d array

array([ 2, 15, 20])

In [41]:
np.divide(a,c) #divide opertion of 2 d array

array([0.5 , 0.6 , 1.25])

SUMMARY OPERATIONS ------------

In [44]:
import numpy as np
arr=np.random.randint(1,200,(5,3))
arr

array([[101, 131, 119],
       [ 29,  98,  32],
       [130, 119,  39],
       [ 58, 155,  44],
       [ 27, 128, 195]])

In [45]:
arr.shape # calculate number pf rows and column

(5, 3)

In [46]:
np.transpose(arr).shape

(3, 5)

In [48]:
arr123=arr.ravel()
arr123

array([101, 131, 119,  29,  98,  32, 130, 119,  39,  58, 155,  44,  27,
       128, 195])

In [49]:
arr123.max() # for max value

195

In [50]:
arr123.min()# for min value

27

In [51]:
arr123.mean()# for mean value

93.66666666666667

In [53]:
np.median(arr123) # for median

101.0

In [54]:
arr.argmin() # for min position

12

In [55]:
arr.argmax()   # for max position

14

In [56]:
arr.sort() # sorting in ascending order
arr

array([[101, 119, 131],
       [ 29,  32,  98],
       [ 39, 119, 130],
       [ 44,  58, 155],
       [ 27, 128, 195]])

In [57]:
arr[::-1] #for reverse order sorting

array([[ 27, 128, 195],
       [ 44,  58, 155],
       [ 39, 119, 130],
       [ 29,  32,  98],
       [101, 119, 131]])

In [58]:
arr.argsort()# sort acc to indexing

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [59]:
arr.shape

(5, 3)